### ISSUE TITLE
SDRPLAY RSP2

### ISSUE THREAD

**Issue by Martinhj65** [gqrx-sdr/gqrx#1209]
I am using the app that GQRX and it works great for rtl-sdr but I also have a model RSP2 SDRPlay dongle and I want to know what device code I write to make it work with this app.
73 From Mexico.
XEI am using the app that GQRX and it works great for rtl-sdr but I also have a model RSP2 SDRPlay dongle and I want to know what device code I write to make it work with this app
73 From Mexico.
Thank you
![Captura desde 2023-03-26 02-33-32](https://user-images.githubusercontent.com/128963190/227764545-b3e6fb09-586d-43e2-9364-a8fc4a156efc.png)

**Comment by argilo** [comment]
Unfortunately SDRplay hardware is not well supported because it uses a proprietary driver which is difficult to package with open source software.

I would suggest that you build and install either https://github.com/pothosware/SoapySDRPlay2 or https://github.com/pothosware/SoapySDRPlay3 (based on the version of the SDRPlay driver you are using) and then use device string `soapy=0,driver=sdrplay`.
