### ISSUE TITLE
gqrx: error while loading shared libraries: libgnuradio-blocks.so.3.10.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by penguinEnthusiast** [gqrx-sdr/gqrx#1273]
I am trying to use GQRX w/ an RTL-SDR USB dongle. I have downloaded the necessary packages for RTL, have the newest version of GNU Radio, and installed GQRX. 

When I enter "gqrx" in the CLI, the above text is returned. I do not know how to resolve this issue and would like to ask for help. Thank you for any and all assistance!

OS: Linux Mint 21.1
Kernal: Linux 5.15.0-79-generic

**Comment by argilo** [comment]
I suspect that you might have multiple versions of GNU Radio installed. (Perhaps one installed from the package manager, and one built from source.) If so, remove one of the versions before attempting to build and run Gqrx.

Because this error is unlikely to be a problem with Gqrx itself, I'll close off this issue. If you need further support in installing Gqrx, please seek help in the Google group: https://groups.google.com/g/gqrx
