### ISSUE TITLE
Bookmarks tags filter bookmarks list but not FFT spectrum display

### ISSUE THREAD

**Issue by mattames** [gqrx-sdr/gqrx#627]
It would be handy if the bookmarks that are displayed on the FFT spectrum display could be filtered by tags. I have a large number of bookmarks and using the tags is only way I can manage them, while this clears up the bookmarks list, my spectrum FFT is still very cluttered.

**Comment by kolbma** [comment]
Hi @mattames 

Here is a tree https://github.com/kolbma/gqrx/tree/bookmarks-ext which introduces some changes to bookmarks...

One part is that the bookmarks on the plotter are **filtered by tags** like the bookmark table.

There is also another **column** **"Info"** where you can put in some description for the bookmark.
If you use this column, the bookmark.csv file is **not backward compatible**.
So make a backup of your bookmark.csv before. And do **not call it bookmark.csv.bck** in the same folder, because another part is, that saving the bookmarks has changed.
The official version overwrites the existing file. If there is some problem during write (crash, disk full, whatever) your bookmarks are lost. My changeset introduces a failsafe save and uses the before called **bookmark.csv.bck** to backup the current file, before moving a temporary file in place, and deleting the backup on success.

Tags are also editable now. And the plotter reacts to changes on the fly.
And the table is not sorted by default now, but can be sorted by clicking the column headers.
In the context menu there is the possibility to reset the sorting.

I'll test the changes the next days and will make a pull request.
But it would be nice if someone could test my changes, because maybe there are use-cases of bookmarks which I don't think of.
