### ISSUE TITLE
GQRX installation (osmsosdr error)

### ISSUE THREAD

**Issue by vnnspace** [gqrx-sdr/gqrx#952]
Hello. 
I have an issue with the installation of the new version of GQRX.
I did follow the steps.
1. download gqrx by ' git clone https://github.com/csete/gqrx.git'
2. cd ..
3. mkdir build
4. cd build
5. cmake .. ( it was OK but some warning was like ) picture you can find below
![image](https://user-images.githubusercontent.com/58883080/112937073-f7ca0800-9161-11eb-802e-f22cfefaf85a.png)

6. make ( error 2 ) picture of error you can find below
![image](https://user-images.githubusercontent.com/58883080/112936971-c2bdb580-9161-11eb-90a1-3231baec7c6a.png)

It will be very helpful for me to understand why it is not installing....
additionally, I install all gnuradio modules 

sudo apt install libgnuradio-* (picture below)
![image](https://user-images.githubusercontent.com/58883080/112937566-d4ec2380-9162-11eb-826b-285764106a35.png)

if you need more information about understanding please ask.

**Comment by shuyuan-liu** [comment]
In 5, missing `mpir` shouldn't be a problem as the latest version builds fine on my computer without it.

Could I confirm that you have the packages `gnuradio`, `gnuradio-dev`, and `gr-osmosdr` installed? In my understanding, the `libgnuradio-*` packages only provide pre-made libraries for programs to call but not the headers needed for compiling. I don't use Ubuntu so I'm not very sure, but you might also want to try installing `libosmosdr-dev`.

**Comment by vnnspace** [comment]
Thank you for your answer i will answer by screen captch
libosmosdr-dev
![image](https://user-images.githubusercontent.com/58883080/113071791-74132880-9200-11eb-8797-21d23954816e.png)

gnuradio
![image](https://user-images.githubusercontent.com/58883080/113071890-a886e480-9200-11eb-8d85-511d8210c229.png)

gr-osmosdr
![image](https://user-images.githubusercontent.com/58883080/113071952-c8b6a380-9200-11eb-8e07-99aef5f06462.png)

Yes all packages which I know is installed... i am try to understand what I miss

**Comment by shuyuan-liu** [comment]
I honestly don't see anything wrong. I searched my system for where the `disconnect` function is defined, and it seems to be owned by the gnuradio-dev package, which you do have installed.

I would try deleting the gqrx folder, `git clone` it again, and build again according to the instructions. I would avoid using `sudo` except for when installing packages, because that potentially causes permission problems. Could you try that?

**Comment by argilo** [comment]
Since it appears the installation instructions weren't followed correctly and there hasn't been any follow-up response, I'll close this off for now.

**Comment by markjfine** [comment]
FYI

Seems this is something I ran into using gnuradio 3.9.x and gr-osmosdr 2.3. Homebrew won't even provide a good version of gr-osmosdr for the Mac. You get an error that it can't be built.

gr-osmosdr changed everything from std to boost in 2.1 which causes havoc (Homebrew's version of boost might be broken too). The two choices are:
1. Go back to gr-osmosdr 2.0; or
2. Do a global search and replace for all the boost:: references to std::, and put the three BOOST_FOREACH statements back to regular 'for each' statements as they were in 2.0. After that (aside from the Python/SWIG binding process also being broken) everything builds fine. The changes from 2.0 to 2.3 are really only specific to the HackRF code and are very minimal.

**Comment by argilo** [comment]
> 1. Go back to gr-osmosdr 2.0
> 2. Do a global search and replace

I'd suggest using gr-osmosdr's master branch. I removed the references to BOOST_FOREACH that were accidentally added, but not release has happened since that time.

**Comment by markjfine** [comment]
> I'd suggest using gr-osmosdr's master branch. I removed the references to BOOST_FOREACH that were accidentally added, but not release has happened since that time.

As you already know, you are 100% correct. lol

When I built the master branch I interpreted it to have created 0.2.0, because of the very confusing message at the end of cmake: `Building for version: 0.2.0.0 / 0.2.0`. So I thought I had 0.2.0. That build worked, but I thought I might be missing out on something required in 0.2.3. I didn't trust what the repository was giving me and unwittingly 'fixed' everything that was boost / swig in the 0.2.3 tarball that was already fixed in the repository. 🤦🏻‍♂️

Lesson learned: If the repository works, trust the repository. 🤪
